services:
  - type: web
    name: unwind-django
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "your-production-secret-key"
      - key: ALLOWED_HOSTS
        value: "your-subdomain.onrender.com"

    staticPublishPath: staticfiles
