# Generated by Django 5.1.6 on 2025-07-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('category', models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('welnspa', 'Welness and Spa')], default='luxury', help_text='select category', max_length=50, null=True)),
                ('title', models.CharField(max_length=350)),
                ('content', models.TextField(help_text='Write here', null=True)),
            ],
        ),
    ]
