# Generated by Django 5.2.3 on 2025-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flier', models.ImageField(upload_to='events/fliers/')),
                ('thumbnail', models.ImageField(upload_to='events/thumbnails/')),
                ('title', models.CharField(max_length=100)),
                ('brief_text', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
