# Generated by Django 5.2.3 on 2025-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_blogcategory_post_created_at_post_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='brief_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Wellness', 'Wellness'), ('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Food', 'Food'), ('Events', 'Events'), ('Culture', 'Culture'), ('Mindfulness', 'Mindfulness'), ('Inspiration', 'Inspiration'), ('Nature', 'Nature'), ('Guides', 'Guides'), ('Stories', 'Stories'), ('Experiences', 'Experiences')], max_length=50),
        ),
    ]
