# Generated by Django 5.2.3 on 2025-08-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_remove_event_brief_text_remove_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Wellness', 'Wellness'), ('Adventure', 'Adventure'), ('Relaxation', 'Relaxation'), ('Food', 'Food'), ('Events', 'Events'), ('Culture', 'Culture'), ('Mindfulness', 'Mindfulness'), ('Inspiration', 'Inspiration'), ('Nature', 'Nature'), ('Guides', 'Guides'), ('Stories', 'Stories'), ('Experiences', 'Experiences')], default='Travel', max_length=50),
        ),
    ]
