# Generated by Django 5.2.3 on 2025-09-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0006_event_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='event',
            name='badge',
            field=models.CharField(blank=True, choices=[('Featured', 'Featured'), ('Limited', 'Limited'), ('New', 'New'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short teaser used on cards'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='read_minutes',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='hellow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Full post content', null=True),
        ),
    ]
