# Generated by Django 5.2.3 on 2025-11-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Web", "0007_alter_event_options_remove_event_is_expired_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="nominees/photos/")),
                (
                    "story",
                    models.TextField(
                        help_text="Short story about why they deserve to unwind"
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        blank=True, help_text="Without @ symbol", max_length=100
                    ),
                ),
                ("vote_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order on voting page"
                    ),
                ),
            ],
            options={
                "ordering": ["campaign", "order", "-vote_count"],
            },
        ),
        migrations.CreateModel(
            name="VotingCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Nominate to Unwind – November 2025",
                        max_length=255,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Campaign details shown on voting page"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "vote_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=500.0,
                        help_text="Price per vote in Naira",
                        max_digits=10,
                    ),
                ),
                (
                    "rest_points_per_vote",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Rest points earned per vote",
                        max_digits=10,
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaigns/banners/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_name", models.CharField(max_length=255)),
                ("voter_email", models.EmailField(max_length=254)),
                ("voter_phone", models.CharField(max_length=20)),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="Who told you about Unwind Africa?",
                        max_length=255,
                    ),
                ),
                (
                    "vote_quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of votes purchased"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Total amount paid", max_digits=10
                    ),
                ),
                (
                    "rest_points_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="Web.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("paystack_reference", models.CharField(blank=True, max_length=100)),
                ("authorization_url", models.URLField(blank=True)),
                ("access_code", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paystack_response", models.JSONField(blank=True, null=True)),
                (
                    "vote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="Web.vote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="nominee",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominees",
                to="Web.votingcampaign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nominee",
            unique_together={("campaign", "name")},
        ),
    ]
