# Generated by Django 5.2.3 on 2025-11-15 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Web", "0008_nominee_votingcampaign_vote_transaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non_binary", "Non-Binary"),
                            ("prefer_not_to_say", "Prefer Not to Say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="City or Country", max_length=255
                    ),
                ),
                ("referral_source", models.CharField(blank=True, max_length=255)),
                (
                    "interests",
                    models.TextField(blank=True, help_text="Comma-separated interests"),
                ),
                ("google_form_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "google_sheet_row_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RestCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_email", models.EmailField(max_length=254, unique=True)),
                ("member_name", models.CharField(max_length=255)),
                ("member_phone", models.CharField(max_length=20)),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated unique card number",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waitlist", "Waitlist"),
                            ("pending", "Pending Activation"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="waitlist",
                        max_length=20,
                    ),
                ),
                (
                    "waitlist_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "total_rest_points",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total rest points accumulated",
                        max_digits=10,
                    ),
                ),
                ("waitlist_joined_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["waitlist_position", "-waitlist_joined_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_email", models.EmailField(max_length=254, unique=True)),
                ("member_name", models.CharField(max_length=255)),
                (
                    "tokens_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total tokens earned from all activities",
                        max_digits=10,
                    ),
                ),
                (
                    "tokens_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total tokens spent/redeemed",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-tokens_earned"],
            },
        ),
        migrations.CreateModel(
            name="TokenTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earned"),
                            ("spend", "Spent"),
                            ("bonus", "Bonus"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.TextField(
                        help_text="e.g., Voted for November Campaign, Redeemed for discount"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="Related vote/transaction ID",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="Web.tokenwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
