# Generated by Django 5.2.3 on 2025-11-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Web", "0009_communitymember_restcard_tokenwallet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restcard",
            name="card_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated unique card number",
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
    ]
