# Generated by Django 5.2.3 on 2025-11-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Web", "0010_alter_restcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(
                db_index=True,
                help_text="Payment reference - multiple votes can share same payment",
                max_length=100,
            ),
        ),
    ]
