# Generated by Django 5.1.6 on 2026-01-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_pageview_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcampaign',
            name='grand_prize',
            field=models.CharField(blank=True, help_text='Grand prize description', max_length=255),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='grand_prize_description',
            field=models.TextField(blank=True, help_text='Detailed description of grand prize'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='prize_description',
            field=models.TextField(blank=True, help_text='Overall prizes description'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='second_prize',
            field=models.CharField(blank=True, help_text='Second prize description', max_length=255),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='second_prize_description',
            field=models.TextField(blank=True, help_text='Detailed description of second prize'),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline for the campaign', max_length=255),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='third_prize',
            field=models.CharField(blank=True, help_text='Third prize description', max_length=255),
        ),
        migrations.AddField(
            model_name='votingcampaign',
            name='third_prize_description',
            field=models.TextField(blank=True, help_text='Detailed description of third prize'),
        ),
    ]
