# Generated by Django 5.1.6 on 2026-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_votingcampaign_grand_prize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominee',
            name='number',
            field=models.CharField(blank=True, help_text='Nominee number on voting card', max_length=50),
        ),
    ]
