# Generated by Django 5.1.6 on 2026-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_nominee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
