# Generated by Django 5.1.6 on 2026-02-17 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0015_vote_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('description', models.TextField(blank=True)),
                ('age_category', models.CharField(choices=[('0-3', '0-3 years'), ('4-6', '4-6 years'), ('7-10', '7-10 years'), ('11-14', '11-14 years'), ('15+', '15+ years'), ('adult', 'Adult')], max_length=20)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('adventure', 'Adventure'), ('fantasy', 'Fantasy'), ('science-fiction', 'Science Fiction'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('art', 'Art'), ('poetry', 'Poetry'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On Loan'), ('high_demand', 'High Demand'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('isbn', models.CharField(blank=True, help_text='ISBN number (optional)', max_length=20)),
                ('times_borrowed', models.PositiveIntegerField(default=0)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='Web.restcard')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
