# Generated by Django 5.2.3 on 2026-03-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdBritishTrialRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=200)),
                ('child_age', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
