# Generated by Django 5.1.6 on 2026-03-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0017_edbritishtrialregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenRestPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_email', models.EmailField(max_length=254)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('member_phone', models.CharField(blank=True, max_length=20)),
                ('frozen_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rest_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_points_transfers', to='Web.restcard')),
                ('vote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_points_entry', to='Web.vote')),
            ],
            options={
                'verbose_name': 'Frozen Rest Points',
                'verbose_name_plural': 'Frozen Rest Points',
                'ordering': ['-created_at'],
            },
        ),
    ]
