# Generated by Django 5.1.6 on 2026-03-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0018_frozenrestpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenrestpoints',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='frozenrestpoints',
            name='member_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='frozenrestpoints',
            name='points_claimed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='restcard',
            name='status',
            field=models.CharField(choices=[('waitlist', 'Waitlist'), ('pending', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='waitlist', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='frozenrestpoints',
            index=models.Index(fields=['member_email', 'points_claimed'], name='frozen_email_claimed_idx'),
        ),
        migrations.AddIndex(
            model_name='restcard',
            index=models.Index(fields=['status', 'waitlist_joined_at'], name='restcard_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='trans_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['nominee', 'created_at'], name='vote_nom_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['payment_status'], name='vote_status_idx'),
        ),
    ]
