# Generated by Django 5.1.6 on 2026-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0019_alter_frozenrestpoints_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcard',
            name='free_votes_remaining',
            field=models.PositiveIntegerField(default=1, help_text='Free votes remaining for rest card registrants'),
        ),
    ]
