# Generated by Django 5.2.3 on 2026-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0020_add_free_votes_to_restcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcampaign',
            name='nomination_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for submitting nominations (if different from voting end)', null=True),
        ),
    ]
