# Generated by Django 5.2.3 on 2026-03-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0021_votingcampaign_nomination_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcard',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the card email was sent', null=True),
        ),
        migrations.AddField(
            model_name='restcard',
            name='email_viewed_at',
            field=models.DateTimeField(blank=True, help_text='When the user first viewed their card email', null=True),
        ),
    ]
