# Generated by Django 5.2.3 on 2025-09-09 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=160)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbs/')),
                ('flier', models.ImageField(blank=True, null=True, upload_to='events/fliers/')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbs/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created'],
            },
        ),
    ]
