# Generated by Django 5.2.3 on 2025-10-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_alter_event_options_remove_event_is_expired_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Web.blogcategory',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Web.post',),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', '-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Web.event',),
        ),
    ]
